version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk
    steps:
        - checkout
workflow:
  version: 2
  build:
    jobs:
      build:
        filters:
          branches:
            only: gradle-migration