#Circle CI Config File
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - norsesonic-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: norsesonic-{{ checksum "pom.xml" }}

      - run: mvn package
      - store_artifacts:
          path: build/distributions
          destination: distributions
      - store_artifacts:
          path: build/libs
          destination: libs
workflow:
  version: 2
  build:
    jobs:
      build:
        filters:
          branches:
            only:
              -master
              -dev