version: 2
jobs:
  build:
    steps:
        -checkout
        - run:
          name: Echo Out
          command: 'echo Hello World'
workflow:
  version: 2
  build:
    jobs:
      build:
        filters:
          branches:
            only: gradle-migration