version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk
    steps:
        - checkout
        - restore_cache:
            keys:
              - gradle-{{ checksum "build.gradle" }}
        - run: gradle airsonic-main: war
        - save_cache:
            paths:
              - ~/.gradle
            key: gradle-{{ checksum "build.gradle" }}
        - store_artifacts:
            path: build/distributions
            destination: distributions
        - store_artifacts:
            path: build/libs
            destination: libs
workflow:
  version: 2
  build:
    jobs:
      build:
        filters:
          branches:
            only: gradle-migration